class AibanhangApplyRequest {
  final String productName;
  final String insurancePeriod;
  final String mergeAccount;
  final String myTeam;
  final String wechat;
  final String contractDate;
  final String reservationSigningTime;
  final String nc;
  final int amount;
  final String annualInvestment;
  final String chineseName;
  final String englishName;
  final String birthday;
  final String sex;
  final String idNumber;
  final String documentNo;
  final String isSmoking;
  final String education;
  final String maritalStatus;
  final String familiesNo;
  final String phone;
  final String email;
  final String address;
  final String addressZipCode;
  final String mailingAddress;
  final String zipCode;
  final String companyName;
  final String unitAddress;
  final String position;
  final String natureOfBusiness;
  final String beneficiaryName;
  final String beneficiaryNamePinyin;
  final String relationShip;
  final String beneficiaryIdNumber;
  final String beneficiaryName2;
  final String beneficiaryNamePinyin2;
  final String relationShip2;
  final String beneficiaryIdNumber2;
  final String monthlyIncome;
  final String monthlyExpenditure;
  final String currentAss;
  final String personalDebt;
  final String mc101;
  final String mcyear;
  final String mcCompany;
  final String mcProductName;
  final String mcAmount;
  final String mcCurrency;
  final String otherRmark;
  final String effective;
  final String height;
  final String weight;
  final String remarks;
  final String insuredChineseName;
  final String insuredEnglishName;
  final String insuredBirthday;
  final String insuredSex;
  final String insuredIdNo;
  final String insuredPassNo;
  final String insuredEducation;
  final String insuredMaritalStatus;
  final String insuredFamiliesNo;
  final String insuredPhone;
  final String insuredEmail;
  final String insuredAddress;
  final String insuredAddressZip;
  final String insuredMailingAddress;
  final String insuredMailingAddressZip;
  final String insuredCompanyName;
  final String insuredUnitAddress;
  final String insuredPosition;
  final String insuredNatureOfBusiness;
  final String insuredMonthlyIncome;
  final String insuredMonthlyExpenditure;
  final String insuredCurrentAss;
  final String insuredPersonalDebt;
  final String insuredMc101;
  final String insuredMcyear;
  final String insuredMcCompany;
  final String insuredMcProductName;
  final String insuredMcAmount;
  final String insuredMcCurrency;
  final String otherRmark2;
  final String insuredEffective;
  final String insuredHeight;
  final String insuredWeight;
  final String insuredRemarks;
  final String idCardFront;
  final String idCardReverse;
  final String passFront;
  final String passReverse;
  final String? insuredIdCardFront;
  final String? insuredIdCardReverse;
  final String? insuredPassFront;
  final String? insuredPassReverse;
  final String? birthCertificateFront;

  AibanhangApplyRequest({
    this.productName = "",
    this.insurancePeriod = "",
    this.mergeAccount = "",
    this.myTeam = "",
    this.wechat = "",
    this.contractDate = "",
    this.reservationSigningTime = "",
    this.nc = "",
    this.amount = 0,
    this.annualInvestment = "",
    this.chineseName = "",
    this.englishName = "",
    this.birthday = "",
    this.sex = "",
    this.idNumber = "",
    this.documentNo = "",
    this.isSmoking = "",
    this.education = "",
    this.maritalStatus = "",
    this.familiesNo = "",
    this.phone = "",
    this.email = "",
    this.address = "",
    this.addressZipCode = "",
    this.mailingAddress = "",
    this.zipCode = "",
    this.companyName = "",
    this.unitAddress = "",
    this.position = "",
    this.natureOfBusiness = "",
    this.beneficiaryName = "",
    this.beneficiaryNamePinyin = "",
    this.relationShip = "",
    this.beneficiaryIdNumber = "",
    this.beneficiaryName2 = "",
    this.beneficiaryNamePinyin2 = "",
    this.relationShip2 = "",
    this.beneficiaryIdNumber2 = "",
    this.monthlyIncome = "",
    this.monthlyExpenditure = "",
    this.currentAss = "",
    this.personalDebt = "",
    this.mc101 = "",
    this.mcyear = "",
    this.mcCompany = "",
    this.mcProductName = "",
    this.mcAmount = "",
    this.mcCurrency = "",
    this.otherRmark = "",
    this.effective = "",
    this.height = "",
    this.weight = "",
    this.remarks = "",
    this.insuredChineseName = "",
    this.insuredEnglishName = "",
    this.insuredBirthday = "",
    this.insuredSex = "",
    this.insuredIdNo = "",
    this.insuredPassNo = "",
    this.insuredEducation = "",
    this.insuredMaritalStatus = "",
    this.insuredFamiliesNo = "",
    this.insuredPhone = "",
    this.insuredEmail = "",
    this.insuredAddress = "",
    this.insuredAddressZip = "",
    this.insuredMailingAddress = "",
    this.insuredMailingAddressZip = "",
    this.insuredCompanyName = "",
    this.insuredUnitAddress = "",
    this.insuredPosition = "",
    this.insuredNatureOfBusiness = "",
    this.insuredMonthlyIncome = "",
    this.insuredMonthlyExpenditure = "",
    this.insuredCurrentAss = "",
    this.insuredPersonalDebt = "",
    this.insuredMc101 = "",
    this.insuredMcyear = "",
    this.insuredMcCompany = "",
    this.insuredMcProductName = "",
    this.insuredMcAmount = "",
    this.insuredMcCurrency = "",
    this.otherRmark2 = "",
    this.insuredEffective = "",
    this.insuredHeight = "",
    this.insuredWeight = "",
    this.insuredRemarks = "",
    this.idCardFront = "",
    this.idCardReverse = "",
    this.passFront = "",
    this.passReverse = "",
    this.insuredIdCardFront,
    this.insuredIdCardReverse,
    this.insuredPassFront,
    this.insuredPassReverse,
    this.birthCertificateFront,
  });
}
