class FjApplyRequest {
  final String productName;
  final String paymentMethod;
  final String mergeAccount;
  final String myTeam;
  final String wechat;
  final String contractDate;
  final String reservationSigningTime;
  final String nc;
  final int amount;
  final String annualInvestment;
  final String investmentAmount;
  final String chineseName;
  final String englishName;
  final String birthday;
  final String sex;
  final String idNumber;
  final String documentNo;
  final String passValid;
  final String endorsementValid;
  final String endorsementType;
  final String education;
  final String maritalStatus;
  final String familiesNo;
  final String phone;
  final String email;
  final String address;
  final String addressZipCode;
  final String mailingAddress;
  final String zipCode;
  final String companyName;
  final String position;
  final String unitAddress;
  final String natureOfBusiness;
  final String beneficiaryName;
  final String relationShip;
  final String beneficiaryIdNumber;
  final String beneficiaryName2;
  final String relationShip2;
  final String beneficiaryIdNumber2;
  final String monthlyIncome;
  final String monthlyExpenditure;
  final String currentAss;
  final String personalDebt;
  final String mc101;
  final String mcyear;
  final String effective;
  final String insuredChineseName;
  final String insuredEnglishName;
  final String insuredBirthday;
  final String insuredSex;
  final String insuredIdNo;
  final String insuredPassNo;
  final String insuredEducation;
  final String insuredAddress;
  final String insuredAddressZip;
  final String insuredMailingAddress;
  final String insuredMailingAddressZip;
  final String insuredRemarks;
  final String idCardFront;
  final String idCardReverse;
  final String passFront;
  final String passReverse;

  FjApplyRequest({
    this.productName = "",
    this.paymentMethod = "",
    this.mergeAccount = "",
    this.myTeam = "",
    this.wechat = "",
    this.contractDate = "",
    this.reservationSigningTime = "",
    this.nc = "",
    this.amount = 0,
    this.annualInvestment = "",
    this.investmentAmount = "",
    this.chineseName = "",
    this.englishName = "",
    this.birthday = "",
    this.sex = "",
    this.idNumber = "",
    this.documentNo = "",
    this.passValid = "",
    this.endorsementValid = "",
    this.endorsementType = "",
    this.education = "",
    this.maritalStatus = "",
    this.familiesNo = "",
    this.phone = "",
    this.email = "",
    this.address = "",
    this.addressZipCode = "",
    this.mailingAddress = "",
    this.zipCode = "",
    this.companyName = "",
    this.position = "",
    this.unitAddress = "",
    this.natureOfBusiness = "",
    this.beneficiaryName = "",
    this.relationShip = "",
    this.beneficiaryIdNumber = "",
    this.beneficiaryName2 = "",
    this.relationShip2 = "",
    this.beneficiaryIdNumber2 = "",
    this.monthlyIncome = "",
    this.monthlyExpenditure = "",
    this.currentAss = "",
    this.personalDebt = "",
    this.mc101 = "",
    this.mcyear = "",
    this.effective = "",
    this.insuredChineseName = "",
    this.insuredEnglishName = "",
    this.insuredBirthday = "",
    this.insuredSex = "",
    this.insuredIdNo = "",
    this.insuredPassNo = "",
    this.insuredEducation = "",
    this.insuredAddress = "",
    this.insuredAddressZip = "",
    this.insuredMailingAddress = "",
    this.insuredMailingAddressZip = "",
    this.insuredRemarks = "",
    this.idCardFront = "",
    this.idCardReverse = "",
    this.passFront = "",
    this.passReverse = "",
  });
}
