class Jy101Jy105ApplyRequest {
  final String productname;
  final String accountstrs;
  final String accompanyingnumber;
  final String myteam;
  final String wechat;
  final String contractdate;
  final String reservationsigningtime;
  final String nc;
  final int amount;
  final String chineselastname;
  final String chinesename;
  final String englishname;
  final String englishlastname;
  final String birthday;
  final String sex;
  final String idnumber;
  final String documentno;
  final String passvalid;
  final String endorsementvalid;
  final String endorsementtype;
  final String education;
  final String maritalstatus;
  final String familiesno;
  final String phone;
  final String email;
  final String address;
  final String addresszipcode;
  final String mailingaddress;
  final String zipcode;
  final String companyname;
  final String position;
  final String unitaddress;
  final String natureofbusiness;
  final String beneficiaryname;
  final String relationship;
  final String beneficiaryidnumber;
  final String beneficiaryname2;
  final String relationship2;
  final String beneficiaryidnumber2;
  final String monthlyincome;
  final String monthlyexpenditure;
  final String currentass;
  final String personaldebt;
  final String financialnotes;
  final String mc101;
  final String mcyear;
  final String effective;
  final String insuredlastchinesename;
  final String insuredchinesename;
  final String insuredlastenglishname;
  final String insuredenglishname;
  final String insuredbirthday;
  final String insuredsex;
  final String insuredidno;
  final String insuredpassno;
  final String insurededucation;
  final String insuredaddress;
  final String insuredaddresszip;
  final String insuredmailingaddress;
  final String insuredmailingaddresszip;
  final String insuredremarks;
  final String idcardfront;
  final String idcardreverse;
  final String passfront;
  final String passreverse;

  Jy101Jy105ApplyRequest({
  this.productname = "",
  this.accountstrs = "",
  this.accompanyingnumber = "",
  this.myteam = "",
  this.wechat = "",
  this.contractdate = "",
  this.reservationsigningtime = "",
  this.nc = "",
  this.amount = 0,
  this.chineselastname = "",
  this.chinesename = "",
  this.englishname = "",
  this.englishlastname = "",
  this.birthday = "",
  this.sex = "",
  this.idnumber = "",
  this.documentno = "",
  this.passvalid = "",
  this.endorsementvalid = "",
  this.endorsementtype = "",
  this.education = "",
  this.maritalstatus = "",
  this.familiesno = "",
  this.phone = "",
  this.email = "",
  this.address = "",
  this.addresszipcode = "",
  this.mailingaddress = "",
  this.zipcode = "",
  this.companyname = "",
  this.position = "",
  this.unitaddress = "",
  this.natureofbusiness = "",
  this.beneficiaryname = "",
  this.relationship = "",
  this.beneficiaryidnumber = "",
  this.beneficiaryname2 = "",
  this.relationship2 = "",
  this.beneficiaryidnumber2 = "",
  this.monthlyincome = "",
  this.monthlyexpenditure = "",
  this.currentass = "",
  this.personaldebt = "",
  this.financialnotes = "",
  this.mc101 = "",
  this.mcyear = "",
  this.effective = "",
  this.insuredlastchinesename = "",
  this.insuredchinesename = "",
  this.insuredlastenglishname = "",
  this.insuredenglishname = "",
  this.insuredbirthday = "",
  this.insuredsex = "",
  this.insuredidno = "",
  this.insuredpassno = "",
  this.insurededucation = "",
  this.insuredaddress = "",
  this.insuredaddresszip = "",
  this.insuredmailingaddress = "",
  this.insuredmailingaddresszip = "",
  this.insuredremarks = "",
  this.idcardfront = "",
  this.idcardreverse = "",
  this.passfront = "",
  this.passreverse = "",
  });
  }