class SecuritiesAccountApplyRequest {
  final String address;
  final String birthday;
  final String capitalLossRisk;
  final String cbbc;
  final String chineseName;
  final String companyName;
  final String companyPhone;
  final String currentAsset;
  final String derivativeKnow;
  final String education;
  final String email;
  final String englishName;
  final String futures;
  final String idCardFront;
  final String idCardReverse;
  final String idNumber;
  final String investmentGoal;
  final String investmentPurpose;
  final String mailingAddress;
  final String maritalStatus;
  final String monthlyExpenditure;
  final String monthlyIncome;
  final String countryId;
  final String natureBusiness;
  final String openAccountDate;
  final String openAccountTime;
  final String options;
  final String otherExperience;
  final String otherInvest;
  final String otherPurpose;
  final String passFront;
  final String passReverse;
  final String personalDebt;
  final String phone;
  final String position;
  final String serviceYear;
  final String sex;
  final String stock;
  final String unitAddress;
  final String warrent;

  SecuritiesAccountApplyRequest({
    this.address = "",
    this.birthday = "",
    this.capitalLossRisk = "",
    this.cbbc = "",
    this.chineseName = "",
    this.companyName = "",
    this.companyPhone = "",
    this.currentAsset = "",
    this.derivativeKnow = "",
    this.education = "",
    this.email = "",
    this.englishName = "",
    this.futures = "",
    this.idCardFront = "",
    this.idCardReverse = "",
    this.idNumber = "",
    this.investmentGoal = "",
    this.investmentPurpose = "",
    this.mailingAddress = "",
    this.maritalStatus = "",
    this.monthlyExpenditure = "",
    this.monthlyIncome = "",
    this.countryId = "",
    this.natureBusiness = "",
    this.openAccountDate = "",
    this.openAccountTime = "",
    this.options = "",
    this.otherExperience = "",
    this.otherInvest = "",
    this.otherPurpose = "",
    this.passFront = "",
    this.passReverse = "",
    this.personalDebt = "",
    this.phone = "",
    this.position = "",
    this.serviceYear = "",
    this.sex = "",
    this.stock = "",
    this.unitAddress = "",
    this.warrent = "",
  });
}
