class ZabApplyRequest {
  final String insurancePeriod;
  final String insuredSmoking;
  final String mergeAccount;
  final String myTeam;
  final String wechat;
  final String contractDate;
  final String reservationSigningTime;
  final String nc;
  final int amount;
  final String annualPremium;
  final String chineseName;
  final String englishName;
  final String birthday;
  final String sex;
  final String idNumber;
  final String documentNo;
  final int smoking;
  final String education;
  final String maritalStatus;
  final String familiesNo;
  final String phone;
  final String email;
  final String address;
  final String addressZipCode;
  final String mailingAddress;
  final String zipCode;
  final String companyName;
  final String unitAddress;
  final String position;
  final String natureOfBusiness;
  final String beneficiaryName;
  final String beneficiaryPy;
  final String relationShip;
  final String beneficiaryIdNumber;
  final String beneficiaryName2;
  final String beneficiaryPy2;
  final String relationShip2;
  final String beneficiaryIdNumber2;
  final String monthlyIncome;
  final String monthlyExpenditure;
  final String currentAss;
  final String personalDebt;
  final String mc101;
  final String mcyear;
  final String buyCompany;
  final String product;
  final String quota;
  final String currency;
  final String otherRmark;
  final String effective;
  final String height;
  final String weight;
  final String healthNote;
  final String insuredChineseName;
  final String insuredEnglishName;
  final String insuredBirthday;
  final String insuredSex;
  final String insuredIdNo;
  final String insuredPassNo;
  final String insuredPhone;
  final String insuredMail;
  final String insuredEducation;
  final String insuredMarriage;
  final String insuredSupport;
  final String insuredIdAddress;
  final String insuredIdCode;
  final String insuredMailingAddress;
  final String insuredMailingCode;
  final String insuredCompany;
  final String insuredCompanyAdress;
  final String insuredPosition;
  final String insuredBusinessNature;
  final String insuredIncome;
  final String insuredExpenses;
  final String insuredCurrentAssets;
  final String insuredDebt;
  final String insuredMc;
  final String insuredYear;
  final String insuredCname;
  final String insuredProduct;
  final String insuredEd;
  final String insuredCurrency;
  final String otherRmark2;
  final String insuredPeriod;
  final String insuredHeight;
  final String insuredWeight;
  final String insuredHealthNote;
  final String idCardFront;
  final String idCardReverse;
  final String passFront;
  final String passReverse;
  final String? insuredIdCardFront;
  final String? insuredIdCardReverse;
  final String? insuredPassFront;
  final String? insuredPassReverse;
  final String? birthCertificate;

  ZabApplyRequest({
    this.insurancePeriod = "",
    this.insuredSmoking = "",
    this.mergeAccount = "",
    this.myTeam = "",
    this.wechat = "",
    this.contractDate = "",
    this.reservationSigningTime = "",
    this.nc = "",
    this.amount = 0,
    this.annualPremium = "",
    this.chineseName = "",
    this.englishName = "",
    this.birthday = "",
    this.sex = "",
    this.idNumber = "",
    this.documentNo = "",
    this.smoking = 0,
    this.education = "",
    this.maritalStatus = "",
    this.familiesNo = "",
    this.phone = "",
    this.email = "",
    this.address = "",
    this.addressZipCode = "",
    this.mailingAddress = "",
    this.zipCode = "",
    this.companyName = "",
    this.unitAddress = "",
    this.position = "",
    this.natureOfBusiness = "",
    this.beneficiaryName = "",
    this.beneficiaryPy = "",
    this.relationShip = "",
    this.beneficiaryIdNumber = "",
    this.beneficiaryName2 = "",
    this.beneficiaryPy2 = "",
    this.relationShip2 = "",
    this.beneficiaryIdNumber2 = "",
    this.monthlyIncome = "",
    this.monthlyExpenditure = "",
    this.currentAss = "",
    this.personalDebt = "",
    this.mc101 = "",
    this.mcyear = "",
    this.buyCompany = "",
    this.product = "",
    this.quota = "",
    this.currency = "",
    this.otherRmark = "",
    this.effective = "",
    this.height = "",
    this.weight = "",
    this.healthNote = "",
    this.insuredChineseName = "",
    this.insuredEnglishName = "",
    this.insuredBirthday = "",
    this.insuredSex = "",
    this.insuredIdNo = "",
    this.insuredPassNo = "",
    this.insuredPhone = "",
    this.insuredMail = "",
    this.insuredEducation = "",
    this.insuredMarriage = "",
    this.insuredSupport = "",
    this.insuredIdAddress = "",
    this.insuredIdCode = "",
    this.insuredMailingAddress = "",
    this.insuredMailingCode = "",
    this.insuredCompany = "",
    this.insuredCompanyAdress = "",
    this.insuredPosition = "",
    this.insuredBusinessNature = "",
    this.insuredIncome = "",
    this.insuredExpenses = "",
    this.insuredCurrentAssets = "",
    this.insuredDebt = "",
    this.insuredMc = "",
    this.insuredYear = "",
    this.insuredCname = "",
    this.insuredProduct = "",
    this.insuredEd = "",
    this.insuredCurrency = "",
    this.otherRmark2 = "",
    this.insuredPeriod = "",
    this.insuredHeight = "",
    this.insuredWeight = "",
    this.insuredHealthNote = "",
    this.idCardFront = "",
    this.idCardReverse = "",
    this.passFront = "",
    this.passReverse = "",
    this.insuredIdCardFront,
    this.insuredIdCardReverse,
    this.insuredPassFront,
    this.insuredPassReverse,
    this.birthCertificate,
  });
}
