// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0UTZS4H8p2Gs8X_-tThNFKLwk4m0efx8',
    appId: '1:349332183949:web:d2f896113d06bc81f13bc4',
    messagingSenderId: '349332183949',
    projectId: 'yandemofcm',
    authDomain: 'yandemofcm.firebaseapp.com',
    storageBucket: 'yandemofcm.appspot.com',
    measurementId: 'G-3WY0Z2WB8Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvRqwZJjvsirvSePveesgmI2uv7nnags0',
    appId: '1:349332183949:android:5f07882e9b65f027f13bc4',
    messagingSenderId: '349332183949',
    projectId: 'yandemofcm',
    storageBucket: 'yandemofcm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBLmpo7tk3TUu3YsMc9pVAaCu75lpD9eQ',
    appId: '1:349332183949:ios:2f9be7ebc8905670f13bc4',
    messagingSenderId: '349332183949',
    projectId: 'yandemofcm',
    storageBucket: 'yandemofcm.appspot.com',
    iosBundleId: 'com.example.yanDemoFcm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBLmpo7tk3TUu3YsMc9pVAaCu75lpD9eQ',
    appId: '1:349332183949:ios:9041a4f9bd389986f13bc4',
    messagingSenderId: '349332183949',
    projectId: 'yandemofcm',
    storageBucket: 'yandemofcm.appspot.com',
    iosBundleId: 'com.example.yanDemoFcm.RunnerTests',
  );
}
